AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pay-money

  Sample SAM Template for pay-money

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  PayMoneyFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: pay_money/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        PayMoney:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /pay-money
            Method: get
            RequestParameters:
              - method.request.querystring.numbers:
                 Required: true

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PayMoneyApi:
    Description: "API Gateway endpoint URL for Prod stage for Pay Money function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/pay-money/"
  PayMoneyFunction:
    Description: "Pay Money Lambda Function ARN"
    Value: !GetAtt PayMoneyFunction.Arn
  PayMoneyFunctionIamRole:
    Description: "Implicit IAM Role created for Pay Money function"
    Value: !GetAtt PayMoneyFunctionRole.Arn
